### ISSUE TITLE
Cannot login with second Google account after Signing Out

### ISSUE THREAD

**Issue by YaMo97** [UdacityAndroidBasicsScholarship/audacity#41]
### Expected Behavior

After Signing Out from Options Menu and then trying Signing in again, list of Google Accounts must be shown again.

### Actual Behavior 

On signing in again after signing out, list of Accounts is not displayed. Instead, it logs in using the previous account.

### Steps to Reproduce

_(Requires 2 google accounts to understand and reproduce)_

* Open Welcome Page. Tap `Sign In with Google` button. List of Google Accounts is displayed to choose from.
* Sign In using `Account 1`. Home Page opens up.
* Sign Out from `Account 1`. (From options menu). Welcome page opens up again.
* Again Tap `Sign In with Google`. This time list of account is not shown. Instead, it automatically logins using the `Account 1`

**Comment by kartikohri1712** [comment]
I have started working on it. Will soon submit a PR.

**Comment by kartikohri1712** [comment]
#42 PR To solve the issue.

**Comment by sabdar18** [comment]
@kartikohri1712  raise a PR on branch2

**Comment by sabdar18** [comment]
Issue resolved with #45  by @kartikohri1712
